// <auto-generated />
namespace TeamworkSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Student : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student));
        
        string IMigrationMetadata.Id
        {
            get { return "201704202034243_Student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
